packages:
  - packages/*
  - internal/*
  - internal/lint-configs/*
  - apps/*
  - scripts/*
  - docs/*
catalog:
  "jiti": "^2.4.2"
  "unbuild": "^3.5.0"
  "vite": "6.2.1"
  "typescript": "5.8.2"
  "@types/node": "22.13.10"
  "turbo": "2.4.4"
  "rimraf": "^6.0.1"
  "lint-staged": "^15.5.0"
  "husky": "^9.1.7"
  "rollup": "4.35.0"
  "rollup-plugin-visualizer": "^5.14.0"
  "@eslint/js": "^9.22.0"
  "eslint": "^9.22.0"
  "eslint-config-prettier": "^10.1.1"
  "eslint-plugin-vue": "^10.0.0"
  "globals": "^16.0.0"
  "typescript-eslint": "^8.26.1"
  "vue-eslint-parser": "^10.1.1"
  "eslint-plugin-unused-imports": "4.1.4"
  "eslint-plugin-command": "3.1.0"
  "eslint-plugin-import-x": "^4.7.0"
  "prettier": "3.5.3"
  "stylelint": "^16.16.0"
  "stylelint-config-recommended-vue": "^1.6.0"
  "stylelint-config-standard": "^37.0.0"
  "stylelint-config-standard-scss": "^14.0.0"
  "postcss": "^8.5.3"
  "postcss-antd-fixes": "^0.2.0"
  "postcss-html": "^1.8.0"
  "postcss-import": "^16.1.0"
  "postcss-preset-env": "^10.1.5"
  "postcss-scss": "^4.0.9"
  "stylelint-config-recommended": "15.0.0"
  "stylelint-scss": "6.11.1"
  "@stylistic/stylelint-plugin": "^3.1.2"
