packages:
  - packages/*
  - internal/*
  - internal/lint-configs/*
  - apps/*
  - scripts/*
  - docs/*
catalog:
  "jiti": "^2.4.2"
  "unbuild": "^3.5.0"
  "vite": "6.2.1"
  "typescript": "5.8.2"
  "@types/node": "22.13.10"
  "turbo": "2.4.4"
  "rimraf": "^6.0.1"
  "lint-staged": "^15.5.0"
  "husky": "^9.1.7"
  "rollup": "4.35.0"
  "rollup-plugin-visualizer": "^5.14.0"
  "@eslint/js": "^9.22.0"
  "eslint": "^9.22.0"
  "eslint-config-prettier": "^10.1.1"
  "eslint-plugin-vue": "^10.0.0"
  "globals": "^16.0.0"
  "typescript-eslint": "^8.26.1"
  "vue-eslint-parser": "^10.1.1"
  "eslint-plugin-unused-imports": "4.1.4"
  "eslint-plugin-command": "3.1.0"
  "eslint-plugin-import-x": "^4.7.0"
