packages:
  - packages/*
  - internal/*
  - internal/lint-configs/*
  - apps/*
  - scripts/*
  - docs/*
catalog:
  "jiti": "^2.4.2"
  "unbuild": "^3.5.0"
  "vite": "6.2.1"
  "typescript": "5.8.2"
  "@types/node": "22.13.10"
  "turbo": "2.4.4"
  "rimraf": "^6.0.1"
  "lint-staged": "^15.5.0"
  "husky": "^9.1.7"
